# -*- coding: utf-8 -*-
"""ensemble_kg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXdHAY7qd9UE8CM6w0n78qm5-cd18WJi
"""

import json
import random
import re
import pickle
from pathlib import Path
from typing import Optional, Tuple, Dict, List

import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt

import networkx as nx
from scipy.sparse import csr_matrix, hstack

from sklearn.feature_extraction.text import TfidfVectorizer, strip_accents_unicode
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import VotingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    ConfusionMatrixDisplay,
    f1_score,
)

SEED = 30
random.seed(SEED)
np.random.seed(SEED)

nltk.download('stopwords')
stop_words = nltk.corpus.stopwords.words('portuguese')

STRIP_ACCENTS = "unicode"

def normalize_stopwords(words: List[str], strip_accents: Optional[str]) -> List[str]:
    out = []
    for w in words:
        w = str(w).lower()
        if strip_accents == "unicode":
            w = strip_accents_unicode(w)
        out.append(w)
    return sorted(set(out))

stop_words_vec = normalize_stopwords(stop_words, STRIP_ACCENTS)

print("Stopwords PT (originais):", len(stop_words))
print("Stopwords PT (normalizadas p/ TF-IDF):", len(stop_words_vec))
print("SEED:", SEED)
print("STRIP_ACCENTS:", STRIP_ACCENTS)

def resolve_path(preferred_path: str, filename_fallback: Optional[str] = None) -> Path:
    """
    Tenta achar o arquivo:
    1) no caminho preferido (ex: corpus/train.jsonl)
    2) relativo ao cwd
    3) em ./, ./corpus, ./outputs pelo nome fallback
    4) busca recursiva (primeiro match)
    """
    preferred = Path(preferred_path)
    candidates = []

    candidates.append(preferred)
    candidates.append(Path.cwd() / preferred)

    if filename_fallback:
        candidates.append(Path.cwd() / filename_fallback)
        candidates.append(Path.cwd() / "corpus" / filename_fallback)
        candidates.append(Path.cwd() / "outputs" / filename_fallback)

    for c in candidates:
        if c.exists() and c.is_file():
            return c.resolve()

    name_to_find = filename_fallback or preferred.name
    matches = [m for m in Path.cwd().rglob(name_to_find) if m.is_file()]

    if matches:
        return matches[0].resolve()

    raise FileNotFoundError(
        f"Não encontrei '{preferred_path}'. Também tentei '{name_to_find}' em ./, ./corpus, ./outputs e busca recursiva.\n"
        f"Diretório atual: {Path.cwd()}"
    )

def load_jsonl(path: Path) -> pd.DataFrame:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as e:
                raise ValueError(f"JSON inválido em {path} na linha {i}: {e}") from e

    if not rows:
        raise ValueError(f"O arquivo {path} está vazio (ou só com linhas em branco).")

    return pd.DataFrame(rows)

def create_x_y(df: pd.DataFrame) -> Tuple[pd.Series, pd.Series]:
    if "text" not in df.columns or "label" not in df.columns:
        raise ValueError(f"Esperado colunas 'text' e 'label', mas encontrei: {list(df.columns)}")
    x = df["text"].astype(str)
    y = df["label"]
    if x.isna().any():
        raise ValueError("Há valores nulos em 'text'.")
    if y.isna().any():
        raise ValueError("Há valores nulos em 'label'.")
    return x, y

def show_label_stats(y: pd.Series, name: str) -> None:
    counts = y.value_counts(dropna=False)
    print(f"\nDistribuição de classes ({name}):")
    print(counts)
    print("Total:", counts.sum(), "| Classes:", len(counts))

def check_overlap(x_a: pd.Series, x_b: pd.Series, name_a: str, name_b: str) -> None:
    set_a = set(x_a.astype(str).tolist())
    set_b = set(x_b.astype(str).tolist())
    inter = set_a.intersection(set_b)
    print(f"\nOverlap {name_a} ∩ {name_b}: {len(inter)}")
    if len(inter) > 0:
        examples = list(inter)[:3]
        print("Exemplos (até 3):")
        for e in examples:
            print("-", e[:160].replace("\n", " "), "...")

TRAIN_PATH = resolve_path("corpus/train.jsonl", filename_fallback="train.jsonl")
TEST_PATH  = resolve_path("corpus/test.jsonl", filename_fallback="test.jsonl")

print("Paths resolvidos:")
print("TRAIN:", TRAIN_PATH)
print("TEST :", TEST_PATH)

df_train = load_jsonl(TRAIN_PATH)
df_test  = load_jsonl(TEST_PATH)

x_train, y_train = create_x_y(df_train)
x_test, y_test   = create_x_y(df_test)

print("\nTamanhos:", {"train": len(df_train), "test": len(df_test)})

show_label_stats(y_train, "train")
show_label_stats(y_test, "test")

check_overlap(x_train, x_test, "train", "test")

GRAPH_EMB_DIM = 4
GRAPH_EMB_EXTRA = 2
GRAPH_FEATURE_DIM = GRAPH_EMB_DIM + GRAPH_EMB_EXTRA

TOKEN_RE = re.compile(r"[A-Za-zÀ-ÖØ-öø-ÿ]+", re.UNICODE)

def tokenize_for_graph(text: str) -> List[str]:
    return [t.lower() for t in TOKEN_RE.findall(text)]

def read_gpickle_robust(path: Path):
    try:
        return nx.read_gpickle(path)
    except Exception:
        with path.open("rb") as f:
            return pickle.load(f)

def nx_to_sparse_adjacency(G: nx.Graph, nodelist: List[str], weight: str = "weight") -> csr_matrix:
    if hasattr(nx, "to_scipy_sparse_array"):
        A = nx.to_scipy_sparse_array(G, nodelist=nodelist, weight=weight, dtype=float, format="csr")
        return csr_matrix(A)
    return nx.to_scipy_sparse_matrix(G, nodelist=nodelist, weight=weight, dtype=float, format="csr")

def build_node_embeddings_svd(
    G: nx.Graph, dim: int, seed: int = 40
) -> Tuple[List[str], Dict[str, int], np.ndarray]:
    """
    Cria embedding por nó com TruncatedSVD na matriz de adjacência ponderada.
    Retorna:
      - nodelist
      - node_to_idx
      - node_emb (n_nodes x dim)
    """
    nodelist = list(G.nodes())
    node_to_idx = {n: i for i, n in enumerate(nodelist)}

    A = nx_to_sparse_adjacency(G, nodelist=nodelist, weight="weight")
    svd = TruncatedSVD(n_components=dim, random_state=seed)
    node_emb = svd.fit_transform(A).astype(np.float32)  # (n_nodes, dim)

    return nodelist, node_to_idx, node_emb

def doc_features_from_graph(texts: pd.Series, node_to_idx: Dict[str, int], node_emb: np.ndarray) -> np.ndarray:
    """
    Para cada texto: média dos embeddings dos nós correspondentes aos tokens que aparecem no grafo
    + cobertura (hits/total_tokens)
    + log1p(hits)
    """
    n = len(texts)
    feats = np.zeros((n, GRAPH_FEATURE_DIM), dtype=np.float32)

    for i, txt in enumerate(texts.astype(str).tolist()):
        toks = tokenize_for_graph(txt)
        if not toks:
            continue

        idxs = [node_to_idx[t] for t in toks if t in node_to_idx]
        hits = len(idxs)
        total = len(toks)

        if hits > 0:
            feats[i, :GRAPH_EMB_DIM] = node_emb[idxs].mean(axis=0)

        coverage = hits / total if total > 0 else 0.0
        feats[i, GRAPH_EMB_DIM] = coverage
        feats[i, GRAPH_EMB_DIM + 1] = np.log1p(hits)

    return feats

COOC_PATH = resolve_path("outputs/KG_cooc.gpickle", filename_fallback="KG_cooc.gpickle")
PPMI_PATH = resolve_path("outputs/KG_ppmi.gpickle", filename_fallback="KG_ppmi.gpickle")
PUN_PATH  = resolve_path("outputs/KG_puncontext.gpickle", filename_fallback="KG_puncontext.gpickle")

print("Paths dos grafos:")
print("COOC:", COOC_PATH)
print("PPMI:", PPMI_PATH)
print("PUN :", PUN_PATH)

G_cooc = read_gpickle_robust(COOC_PATH)
G_ppmi = read_gpickle_robust(PPMI_PATH)
G_pun  = read_gpickle_robust(PUN_PATH)

print("\nTamanhos dos grafos:")
print("COOC nodes/edges:", G_cooc.number_of_nodes(), G_cooc.number_of_edges())
print("PPMI nodes/edges:", G_ppmi.number_of_nodes(), G_ppmi.number_of_edges())
print("PUN  nodes/edges:", G_pun.number_of_nodes(),  G_pun.number_of_edges())

graphs = {
    "Cooc": G_cooc,
    "PPMI": G_ppmi,
    "PunContext": G_pun
}

node_models: Dict[str, Dict[str, object]] = {}
for name, G in graphs.items():
    print(f"\n[Node Embedding] Construindo SVD para {name}...")
    _, node_to_idx, node_emb = build_node_embeddings_svd(G, dim=GRAPH_EMB_DIM, seed=SEED)
    node_models[name] = {"node_to_idx": node_to_idx, "node_emb": node_emb}
    print(f"  OK: {name} -> node_emb shape:", node_emb.shape)

graph_doc_feats: Dict[str, Dict[str, np.ndarray]] = {name: {} for name in graphs.keys()}

for name in graphs.keys():
    print(f"\n[Doc Features] Extraindo features do grafo {name} (train/test)...")
    node_to_idx = node_models[name]["node_to_idx"]
    node_emb    = node_models[name]["node_emb"]

    graph_doc_feats[name]["train"] = doc_features_from_graph(x_train, node_to_idx, node_emb)
    graph_doc_feats[name]["test"]  = doc_features_from_graph(x_test,  node_to_idx, node_emb)

    print("  train:", graph_doc_feats[name]["train"].shape,
          "test:",  graph_doc_feats[name]["test"].shape)

def make_vectorizer() -> TfidfVectorizer:
    return TfidfVectorizer(
        ngram_range=(1, 2),
        stop_words=stop_words_vec,
        lowercase=True,
        strip_accents=STRIP_ACCENTS,
    )

def make_ensemble() -> VotingClassifier:
    rf = RandomForestClassifier(
        n_estimators=100, criterion='entropy', max_depth=15, random_state=40
    )

    lr = LogisticRegression(
        random_state=SEED,
        max_iter=100,
        class_weight="balanced"
    )

    svm_base = LinearSVC(
        random_state=SEED,
        class_weight="balanced"
    )

    svm = CalibratedClassifierCV(
        svm_base,
        method="sigmoid",
        cv=3
    )

    voting = VotingClassifier(
        estimators=[("rf", rf), ("lr", lr), ("svm", svm)],
        voting="soft",
        n_jobs=30
    )
    return voting

def evaluate(name: str, y_true, y_pred, labels=None):
    acc = accuracy_score(y_true, y_pred)
    f1m = f1_score(y_true, y_pred, average="macro")
    print(f"\n=== {name} ===")
    print("Accuracy:", acc)
    print("Macro-F1:", f1m)
    print(classification_report(y_true, y_pred))

    ConfusionMatrixDisplay.from_predictions(
        y_true, y_pred,
        labels=labels,
        cmap=None,
        values_format="d"
    )
    plt.title(f"Matriz de Confusão — {name}")
    plt.show()

    return acc, f1m

def get_graph_block(graph_name: str, split: str) -> np.ndarray:
    return graph_doc_feats[graph_name][split]

def stack_graph_features(blocks: List[np.ndarray]) -> np.ndarray:
    """
    Empilha features *do mesmo split* lado a lado (ex.: Cooc + PPMI + PunContext).
    NÃO mistura train/val/test.
    """
    if not blocks:
        raise ValueError("blocks vazio.")
    return np.hstack(blocks).astype(np.float32)

def fuse_text_and_graph(X_text_csr, Xg_scaled: np.ndarray):
    """Une TF-IDF (sparse) com grafo (dense->csr)."""
    return hstack([X_text_csr, csr_matrix(Xg_scaled)], format="csr")

def run_test_experiment(exp_name: str, graph_names: List[str]):
    """
    Treina APENAS no TRAIN e avalia no TEST.
    (Proibido usar/concatenar TRAIN+VAL em qualquer etapa.)
    """
    vec = make_vectorizer()
    Xtr_text = vec.fit_transform(x_train)
    Xte_text = vec.transform(x_test)

    if not graph_names:
        model = make_ensemble()
        model.fit(Xtr_text, y_train)
        pred = model.predict(Xte_text)
        acc, f1m = evaluate(f"TEST — {exp_name}", y_test, pred, labels=sorted(pd.unique(y_train)))
        return {"setup": exp_name, "test_acc": acc, "test_f1_macro": f1m}

    Xtr_g_raw = stack_graph_features([get_graph_block(g, "train") for g in graph_names])
    Xte_g_raw = stack_graph_features([get_graph_block(g, "test")  for g in graph_names])

    scaler = StandardScaler()
    scaler.fit(Xtr_g_raw)

    Xtr_g = scaler.transform(Xtr_g_raw).astype(np.float32)
    Xte_g = scaler.transform(Xte_g_raw).astype(np.float32)

    Xtr = fuse_text_and_graph(Xtr_text, Xtr_g)
    Xte = fuse_text_and_graph(Xte_text, Xte_g)

    model = make_ensemble()
    model.fit(Xtr, y_train)
    pred = model.predict(Xte)

    acc, f1m = evaluate(f"TEST — {exp_name}", y_test, pred, labels=sorted(pd.unique(y_train)))
    return {"setup": exp_name, "test_acc": acc, "test_f1_macro": f1m}

test_results = [
    run_test_experiment("TF-IDF + Cooc", ["Cooc"]),
    run_test_experiment("TF-IDF + PPMI", ["PPMI"]),
    run_test_experiment("TF-IDF + PunContext", ["PunContext"]),
    run_test_experiment("TF-IDF + ALL (Cooc+PPMI+PunContext)", ["Cooc", "PPMI", "PunContext"]),
]
df_test = pd.DataFrame(test_results)
df_test